### ISSUE TITLE
Bot sends more bytes then requested when client requests a segment of a file

### ISSUE THREAD

**Issue by drd33m** [aler9/dctoolkit#11]
Thankyou for fixing my last issue! I love these library's. When a client has segmented downloading enabled a request is made for 1024 bytes of a file. go-dc tries to send the full or more then the requested bytes back to the client causing the client to erro

```
$ADCGET file TTH/RRHDX55JQCSBI5DDUKSZ56MZEN3NJJ6TFANTRHA 0 1024 ZL1
file TTH/RRHDX55JQCSBI5DDUKSZ56MZEN3NJJ6TFANTRHA 0 1024 ZL1
2020/02/24 14:37:14 [upload] [DrD33M] request tth/RRHDX55JQCSBI5DDUKSZ56MZEN3NJJ6TFANTRHA (s=0 l=1024)
2020/02/24 14:37:14 ERR (upload) [DrD33M]: write tcp4 192.168.1.100:64519->xxx:2020: wsasend: An existing connection was forcibly closed by the remote host.
2020/02/24 14:37:14 [upload] [DrD33M] failed tth/RRHDX55JQCSBI5DDUKSZ56MZEN3NJJ6TFANTRHA
2020/02/24 14:37:14 ERR (connPeer): write tcp4 192.168.1.100:64519->xxx:2020: wsasend: An existing connection was forcibly closed by the remote host.
2020/02/24 14:37:14 [peer] disconnected
```
Client requests s=0 and l=1024 I am guessing for some reason go-dc isn't sending 1024 bytes
```
$ADCGET file TTH/RRHDX55JQCSBI5DDUKSZ56MZEN3NJJ6TFANTRHA 0 23796048 ZL1
file TTH/RRHDX55JQCSBI5DDUKSZ56MZEN3NJJ6TFANTRHA 0 23796048 ZL1
2020/02/24 14:38:19 [upload] [DrD33M] request tth/RRHDX55JQCSBI5DDUKSZ56MZEN3NJJ6TFANTRHA (s=0 l=23796048)
2020/02/24 14:38:20 [sent] 13631488/23796048 (12679.5 KiB/s)
2020/02/24 14:38:21 [upload] [DrD33M] finished tth/RRHDX55JQCSBI5DDUKSZ56MZEN3NJJ6TFANTRHA (s=0 l=23796048)
2020/02/24 14:39:21 [peer] disconnected
```
Client request s=0 and l=23796048 the full file length and go-dc sends the full file and it downloads correctly

**Comment by drd33m** [comment]
Update: I have found the function in the client I am using that is throwing the error

```	virtual size_t write(const void* buf, size_t len) override {
		if(maxBytes < len) {
			throw FileException(STRING(TOO_MUCH_DATA));
		}
		maxBytes -= len;
		return s->write(buf, len);
	}

```

Now I am not sure how go-dcpp is sending more or less bytes unless the log output is wrong to what is actually being sent

**Comment by aler9** [comment]
hello, i finally got some time to investigate into this bug, and i discovered that the part related to segmented uploading was totally missing from the library.
I wrote the library a year ago so i must have forgot, anyway i want to fix any remaining problem, in order to have a modern and solid base that we can use to interact with the DC network, that will remain with us for a long time.

I wrote a patch and tested uploads with segmenting enabled and disabled, with compression enabled and disabled, without problems (i used DC++).
Let me know whether the patch works.

**Comment by drd33m** [comment]
Thankyou so much. Seems I was very off with what I thought. But from my testing all seems to be working now. 
Also it might seem that I am pushing for the issues to be fixed please don't see it that way, I am just trying to give you as much info as I can to help speedup finding the problem as I can see from your GitHub you are a very busy person.
